dist: xenial
language: java
sudo: false
jdk: openjdk15
install: true

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "delta-care"
    token:
      secure: "K1M/MzuIhm2qb7hCaYBsV2Iwz54UAUvxlTmRZdYzTEoKSj4gZZjq5yA75ac0N0ZKdCuZUEOcPSCSWeR4md70C7oESAYWR5B05Sq0/uESyqWaNF3w02rzya8q8pnr8nn73m53LfToFzj7Y/EZ145pzcOdZ7hu0Cytq7BVhodqZkcUI2ZIPLQudwxEW06apj4fqmkNHLOUjFsLJ9sq8SmXBSfahtJcfzW6akNJDJn47uIR3IS2hcw7Ic0a76Gg9eOnvP9+vZMJdkm3a7mq1RcJOyz32V7E2m3+yd5HSGbPIwUNUZIw4ICb3WVIVpj9oZtP0JWogbpAx+VZ46RAtQu9kXCp0+zK4z+GcwhZalKv4JXaKMTIoOlJn3fUnCMngBgweKDcf4dBopLnVUFkGQn1ZBO74CjwXZusqsbNO3+CzbHexZ+B5W2T9tjlm/DP30GA8YPEHV19mjUR2EB0DuXDrK1qG2bOUABeeO9OYU3BQz9T7YjWvvOPOW4tTmPeuGT+oKaWgNypw34gs75wErF8PcP3IvXI8LC939mly9zXgTWTNZ4orsuki/YFek3s6m1l9Msu19I54C1cgaY1f2epjphcQNEF/Nka/3VFzWUGxO9w8r8DZm9u3OaerNORCWfBFtvZDMMecdOMY6eAtGyQbYmJNRxNbj0heW7LqB1mQOY=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache