apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: {{.Values.app.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  action: ALLOW
  rules:
  - from:
    when:
    - key: request.auth.presenter
      values: 
        - deltacare
