kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Values.app.name}}
data:
  application.yml: |-
    spring:
      profiles: dev
      datasource:
        url: jdbc:mysql://empresa-dev.cacvwucgqxal.us-east-2.rds.amazonaws.com/empresa
        username: admin
        password: admin123
      flyway:
        url: jdbc:mysql://empresa-dev.cacvwucgqxal.us-east-2.rds.amazonaws.com
        user: admin
        password: admin123
        schemas: empresa
      jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      cache:
        type: redis
        redis:
          time-to-live: 30000
      redis:
        host: 3.128.159.68
        port: 6379
        password:
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
      kafka:
        bootstrap-servers: ec2-3-128-159-68.us-east-2.compute.amazonaws.com:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
          retries: 3
          properties:
            enable:
              idempotence: true
    logging:
      level:
        root: INFO   
    ---
    spring:
      profiles: prd
      datasource:
        url: jdbc:mysql://empresa-prd.cacvwucgqxal.us-east-2.rds.amazonaws.com/empresa
        username: admin
        password: admin123
      flyway:
        url: jdbc:mysql://empresa-prd.cacvwucgqxal.us-east-2.rds.amazonaws.com
        user: admin
        password: admin123
        schemas: fatura
      jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql: false
      cache:
        type: redis
        redis:
          time-to-live: 30000
      redis:
        host: 3.128.159.68
        port: 6379
        password:
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
      kafka:
        bootstrap-servers: ec2-3-128-159-68.us-east-2.compute.amazonaws.com:9092
        consumer:
          group-id: painel
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-offset-reset: earliest
          enable-auto-commit: false
        listener:
          missing-topics-fatal: false
          ack-mode: manual_immediate
    logging:
      level:
        root: INFO          
