kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Values.app.name}}
data:
  application-prd.yml: |-
    spring:
      datasource:
        url: jdbc:mysql://empresa-prd.cacvwucgqxal.us-east-2.rds.amazonaws.com/empresa
        username: admin
        password: admin123
      flyway:
        url: jdbc:mysql://empresa-prd.cacvwucgqxal.us-east-2.rds.amazonaws.com
        user: admin
        password: admin123
        schemas: empresa