apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
    version: {{.Values.image.tag}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app.name}}
      version: {{.Values.image.tag}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
        version: {{.Values.image.tag}}
    spec:
      serviceAccountName: {{.Values.app.name}}
      containers:
      - name: {{.Values.app.name}}
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        ports:
          - containerPort: {{.Values.service.port}}
            protocol: TCP
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{.Values.app.profile}}
