apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.app.name}}
subjects:
- kind: User
  name: system:serviceaccount:{{.Values.k8s.namespace}}:{{.Values.app.name}}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{.Values.app.name}}
  apiGroup: rbac.authorization.k8s.io
