apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  ports:
  - port: {{.Values.service.port}}
    name: http
  selector:
    app: {{.Values.app.name}}
