spring:
  datasource:
    url: jdbc:mysql://empresa-dev.cacvwucgqxal.us-east-2.rds.amazonaws.com/empresa
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  flyway:
    url: jdbc:mysql://empresa-dev.cacvwucgqxal.us-east-2.rds.amazonaws.com
    user: admin
    password: admin123
    schemas: empresa
    clean-on-validation-error: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 30000
  redis:
    host: 3.128.159.68
    port: 6379
    password:
logging:
  level:
    root: INFO
management:
  metrics:
    enable:
      root: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics