spring:
  datasource:
    url: jdbc:mysql://empresa-dev.cacvwucgqxal.us-east-2.rds.amazonaws.com/empresa
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://empresa-dev.cacvwucgqxal.us-east-2.rds.amazonaws.com
    user: admin
    password: admin123
    schemas: empresa
    clean-on-validation-error: true